### ISSUE TITLE
Cannot find module 'semver'

### ISSUE THREAD

**Issue by mehdyouras** [graphql-nexus/nexus-plugin-prisma#919]
Hello, 
after upgrading to 0.23 i ran into that error on a lambda.

```Error
{
   "errorType":"Runtime.ImportModuleError",
   "errorMessage":"Error: Cannot find module 'semver'\nRequire stack:\n- /var/task/node_modules/nexus-plugin-prisma/dist/index.js\n- /var/task/src/server.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
   "stack":[
      "Runtime.ImportModuleError: Error: Cannot find module 'semver'",
      "Require stack:",
      "- /var/task/node_modules/nexus-plugin-prisma/dist/index.js",
      "- /var/task/src/server.js",
      "- /var/runtime/UserFunction.js",
      "- /var/runtime/index.js",
      "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
      "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
      "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
      "    at Module._compile (internal/modules/cjs/loader.js:1137:30)",
      "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)",
      "    at Module.load (internal/modules/cjs/loader.js:985:32)",
      "    at Function.Module._load (internal/modules/cjs/loader.js:878:14)",
      "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)",
      "    at internal/main/run_main_module.js:17:47"
   ]
}
```

Maybe related to https://github.com/graphql-nexus/nexus-plugin-prisma/commit/5d8cc650c3d353305cba4a28b376ba71796cb9e3 ?

Versions:

- nexus-plugin-prisma: 0.23.0
- @prisma/client: 2.10.0
- @nexus/schema: 0.17.0

**Comment by mehdyouras** [comment]
Adding semver to dependencies should fix the issue
https://github.com/graphql-nexus/nexus-plugin-prisma/pull/920
