### ISSUE TITLE
nexus_1.core.nexusWrappedType is not a function

### ISSUE THREAD

**Issue by MihaiSandor** [graphql-nexus/nexus-plugin-prisma#520]
Prisma CLI version: prisma/1.34.10 (darwin-x64) node-v12.7.0
Prisma server version: 1.34.8

ts-node index.ts
TypeError: nexus_1.core.nexusWrappedType is not a function
    at Object.prismaObjectType (/node_modules/nexus-prisma/src/definitions/objectType.ts:21:15)
    at Object.<anonymous> (/resolvers/Query.ts:12:15)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Module.m._compile (/node_modules/ts-node/src/index.ts:493:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Object.require.extensions.<computed> [as .ts] (/node_modules/ts-node/src/index.ts:496:12)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
error Command failed with exit code 1.

**Comment by sapkra** [comment]
This happens since nexus `0.12.0-rc` and [this commit](https://github.com/prisma-labs/nexus/commit/50bf2981e7e2a461aec767375e0722d796ce2788). A workaround is to use the `0.12.0-beta.14` of nexus.

`nexus-prisma` has to use the new plugin system.

**Comment by macrozone** [comment]
same problem here, does not happen if created with prisma cli `1.34.8`, fails when upgrading to `1.34.10` and regenerate client code.

**Comment by larsivi** [comment]
Assuming it is at all possible to have nexus (in refactored form) work with pre-0.4 nexus-prisma, then I think that should be attempted. I want to use the nexus plugin API, but is for now stuck on Prisma 1 and corresponding nexus-prisma. nexusWrappedType is according to nexus an internal function, so nexus-prisma's use of it is probably possible to rewrite? 

Also, it appears that 0.12.0-beta.14 doesn't have the new Plugin API? At least not exposed.
