### ISSUE TITLE
Typescript error after updating to 0.12.0

### ISSUE THREAD

**Issue by kieusonlam** [graphql-nexus/nexus-plugin-prisma#638]
I got bulk of typescript errors after updating to 0.12.0

```cmd
node_modules/@nexus/schema/dist/builder.d.ts:273:58 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

273     buildObjectType(config: NexusObjectTypeConfig<any>): GraphQLObjectType<any, any, {
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
274         [key: string]: any;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
275     }>;
    ~~~~~~

node_modules/@nexus/schema/dist/builder.d.ts:282:88 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

282     protected buildUnionMembers(unionName: string, members: UnionMembers | undefined): GraphQLObjectType<any, any, {
                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
283         [key: string]: any;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
284     }>[];
    ~~~~~~

node_modules/@nexus/schema/dist/builder.d.ts:285:186 - error TS2314: Generic type 'GraphQLFieldConfigMap' requires 2 type argument(s).

285     protected buildOutputFields(fields: NexusOutputFieldDef[], typeConfig: NexusGraphQLInterfaceTypeConfig | NexusGraphQLObjectTypeConfig, intoObject: GraphQLFieldConfigMap<any, any>): GraphQLFieldConfigMap<any, any, {
    
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
286         [key: string]: any;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
287     }>;
    ~~~~~~

node_modules/@nexus/schema/dist/utils.d.ts:6:47 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

6 export declare const isInterfaceField: (type: GraphQLObjectType<any, any, {
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7     [key: string]: any;
  ~~~~~~~~~~~~~~~~~~~~~~~
8 }>, fieldName: string) => boolean;
  ~~

node_modules/graphql-shield/dist/shield.d.ts:1:38 - error TS2307: Cannot find module 'graphql-middleware'.

1 import { IMiddlewareGenerator } from 'graphql-middleware';
                                       ~~~~~~~~~~~~~~~~~~~~

node_modules/graphql-shield/dist/types.d.ts:2:38 - error TS2307: Cannot find module 'graphql-middleware'.

2 import { IMiddlewareGenerator } from 'graphql-middleware';
                                       ~~~~~~~~~~~~~~~~~~~~

node_modules/nexus/dist/builder.d.ts:273:58 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

273     buildObjectType(config: NexusObjectTypeConfig<any>): GraphQLObjectType<any, any, {
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
274         [key: string]: any;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
275     }>;
    ~~~~~~

node_modules/nexus/dist/builder.d.ts:282:88 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

282     protected buildUnionMembers(unionName: string, members: UnionMembers | undefined): GraphQLObjectType<any, any, {
                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
283         [key: string]: any;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
284     }>[];
    ~~~~~~

node_modules/nexus/dist/builder.d.ts:285:186 - error TS2314: Generic type 'GraphQLFieldConfigMap' requires 2 type argument(s).

285     protected buildOutputFields(fields: NexusOutputFieldDef[], typeConfig: NexusGraphQLInterfaceTypeConfig | NexusGraphQLObjectTypeConfig, intoObject: GraphQLFieldConfigMap<any, any>): GraphQLFieldConfigMap<any, any, {
    
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
286         [key: string]: any;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
287     }>;
    ~~~~~~

node_modules/nexus/dist/utils.d.ts:6:47 - error TS2707: Generic type 'GraphQLObjectType<TSource, TContext>' requires between 0 and 2 type arguments.

6 export declare const isInterfaceField: (type: GraphQLObjectType<any, any, {
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7     [key: string]: any;
  ~~~~~~~~~~~~~~~~~~~~~~~
8 }>, fieldName: string) => boolean;
  ~~

src/server.ts:8:3 - error TS2322: Type 'NexusGraphQLSchema' is not assignable to type 'GraphQLSchema | undefined'.
  Type 'NexusGraphQLSchema' is not assignable to type 'GraphQLSchema'.
    The types returned by 'getQueryType()' are incompatible between these types.
      Type 'Maybe<GraphQLObjectType<any, any>>' is not assignable to type 'Maybe<GraphQLObjectType<any, any, { [key: string]: any; }>>'.
        Type 'GraphQLObjectType<any, any>' is not assignable to type 'Maybe<GraphQLObjectType<any, any, { [key: string]: any; }>>'.
          Types of property 'isTypeOf' are incompatible.
            Type 'import("C:/Users/Lenovo/Desktop/Work/PCNGON/pcngon-be/node_modules/graphql/tsutils/Maybe").default<import("C:/Users/Lenovo/Desktop/Work/PCNGON/pcngon-be/node_modules/graphql/type/definition").GraphQLIsTypeOfFn<any, any>>' is not assignable to type 'import("C:/Users/Lenovo/Desktop/Work/PCNGON/pcngon-be/node_modules/graphql-yoga/node_modules/graphql/tsutils/Maybe").default<import("C:/Users/Lenovo/Desktop/Work/PCNGON/pcngon-be/node_modules/graphql-yoga/node_modules/graphql/type/definition").GraphQLIsTypeOfFn<any, any>>'.
              Type 'GraphQLIsTypeOfFn<any, any>' is not assignable to type 'Maybe<GraphQLIsTypeOfFn<any, any>>'.
                Types of parameters 'info' and 'info' are incompatible.
                  Property 'cacheControl' is missing in type 'import("C:/Users/Lenovo/Desktop/Work/PCNGON/pcngon-be/node_modules/graphql-yoga/node_modules/graphql/type/definition").GraphQLResolveInfo' but required in type 'import("C:/Users/Lenovo/Desktop/Work/PCNGON/pcngon-be/node_modules/graphql/type/definition").GraphQLResolveInfo'.

8   schema,
    ~~~~~~

  node_modules/apollo-cache-control/lib/index.d.ts:22:9
    22         cacheControl: {
               ~~~~~~~~~~~~
    'cacheControl' is declared here.
  node_modules/graphql-yoga/dist/types.d.ts:85:5
    85     schema?: GraphQLSchema;
           ~~~~~~
    The expected type comes from property 'schema' which is declared here on type 'Props<any, any, any>'


Found 11 errors
```

**Comment by Weakky** [comment]
Hey @kieusonlam, could you please provide me your `@nexus/schema` version and `graphql` version?

It's just a guess, but I think you're using the wrong `@nexus/schema` version. Could you make sure you're using `@nexus/schema@^0.13.1` and `graphql@^14.5.0` ?

Thanks 🙏

**Comment by kieusonlam** [comment]
@Weakky Thanks for response. Here is my package.json
```json
{
  "name": "graphql-auth",
  "license": "MIT",
  "scripts": {
    "start": "node dist/server",
    "clean": "rm -rf dist",
    "build": "npm -s run clean && npm -s run generate && tsc",
    "generate": "npm -s run generate:prisma && npm -s run generate:nexus",
    "generate:prisma": "prisma generate",
    "generate:nexus": "ts-node --transpile-only src/schema",
    "postinstall": "npm -s run generate",
    "dev": "ts-node-dev --no-notify --respawn --transpileOnly src/server",
    "dev:migrate": "prisma migrate save --experimental -c && prisma migrate up --experimental -c"
  },
  "dependencies": {
    "@nexus/schema": "^0.13.1",
    "@prisma/client": "^2.0.0-beta.1",
    "bcryptjs": "2.4.3",
    "file-type": "^14.1.4",
    "graphql": "14.5.0",
    "graphql-shield": "7.2.2",
    "graphql-upload": "^10.0.0",
    "graphql-yoga": "1.18.3",
    "jsonwebtoken": "8.5.1",
    "nexus": "0.12.0",
    "nexus-prisma": "0.12.0",
    "sanitize-html": "^1.22.1",
    "shortid": "^2.2.15"
  },
  "devDependencies": {
    "@prisma/cli": "2.0.0-beta.1",
    "@types/bcryptjs": "2.4.2",
    "@types/graphql-upload": "^8.0.3",
    "@types/jsonwebtoken": "8.3.8",
    "@types/node": "13.11.0",
    "@types/shortid": "^0.0.29",
    "@types/ws": "7.2.3",
    "ts-node": "8.8.1",
    "ts-node-dev": "1.0.0-pre.44",
    "typescript": "3.8.3"
  },
  "prettier": {
    "singleQuote": true,
    "semi": false,
    "trailingComma": "all"
  }
}
```

Also here is my schema.ts file if you want to take a look 
```ts
import { nexusPrismaPlugin } from 'nexus-prisma'
import { makeSchema } from '@nexus/schema'
import * as types from './types'

export const schema = makeSchema({
  types,
  plugins: [nexusPrismaPlugin()],
  outputs: {
    schema: __dirname + '/generated/schema.graphql',
    typegen: __dirname + '/generated/nexus.ts',
  },
  typegenAutoConfig: {
    sources: [
      {
        source: '@prisma/client',
        alias: 'client',
      },
      {
        source: require.resolve('./context'),
        alias: 'Context',
      },
    ],
    contextType: 'Context.Context',
  },
})

```

**Comment by jasonkuhrt** [comment]
You have errors like this:

```
node_modules/graphql-shield/dist/types.d.ts:2:38 - error TS2307: Cannot find module 'graphql-middleware'.

2 import { IMiddlewareGenerator } from 'graphql-middleware';
                                       ~~~~~~~~~~~~~~~~~~~~
```

It makes me think something else is going on?

**Comment by kieusonlam** [comment]
update graphql package to 14.6.0 fix everythings for me. Thanks all.
